### Add new job
POST http://localhost:8080/gate/saveNewJob
Content-Type: application/x-www-form-urlencoded

name=QUARTZ_ANALYZE_BTC&interval=5000&stock=BTC


### Load
GET http://localhost:8082/market/load
Content-Type: application/x-www-form-urlencoded
