### Get currency info
POST http://localhost:9000/broker/find-currency-info
Content-Type: application/json

{
  "currencyName": "Доллар США"
}

### Get list of currencies
GET http://localhost:9000/broker/find-all-available-currencies
Content-Type: application/json


### Get bonds info
POST http://localhost:9000/broker/find-bond-info
Content-Type: application/json

{
  "bondName": "Republic of Romania"
}

### Get list of bonds
GET http://localhost:9000/broker/find-all-available-bonds
Content-Type: application/json