###Save new process param
POST http://localhost:9000/cardinal/save-new-process-param
Content-Type: application/json

{
  "name": "trading.instrument.history.earliest.date",
  "numberValue": null,
  "dateValue": "2023-01-01T00:00:00.000000000",
  "stringValue": null
}


###Get list of instruments
GET http://localhost:9000/cardinal/get-api-trade-available-instrument


### Launch trade step manualy
GET http://localhost:9000/cardinal/trade