### Add process params
POST http://localhost:8080/gate/addProcessParam
Content-Type: application/json

{
    "name": "MAX_BALANCE_SHARE_FOR_TRADE",
    "numberValue": 0.35,
    "stringValue": null,
    "dateValue": null
}

### Add job
POST http://localhost:9000/addNewJob
Content-Type: application/json

{
  "name" : "BTC/USD_TRADE",
  "intervalMillis" : 2000.0,
  "stockName": "BTC/USD",
  "jobClassName": "job.org.cardinal.gate.TradingJob",
  "description": "Main trading job",
  "isActive": true,
  "triggerName": "BTC/USD_TRADE_TRIGGER",
  "triggerDescription": "Trigger for trade BTC/USD"
}