### Add process params
POST http://localhost:8080/gate/addProcessParam
Content-Type: application/json

{
    "name": "BTC/USD_CACHE_DEPTH",
    "numberValue": 5000,
    "stringValue": null,
    "dateValue": null
}