server:
  port: 8082
  servlet:
    context-path: /market

market:
  account:
    id: 9b6afcd3-8126-4ca9-a871-e66f409e1d68

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=masada
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
