server:
  port: 8080
  servlet:
    context-path: /gate

masada:
  core:
    url: ${MASADA_CORE_URL:http://localhost:8081/core}

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=masada
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
